### ISSUE TITLE
Update purgecss to the latest version

### ISSUE THREAD

**Issue by XhmikosR** [FullHuman/grunt-purgecss#13]
@Ffloriel could you please update purgecss to the latest version and make a new release?

Thanks!

**Comment by Ffloriel** [comment]
I'll aim to move this repository to the main morepo and update it by the end of the week. I'll let you know.

**Comment by Ffloriel** [comment]
I moved grunt-purgecss to the main monorepo [here](https://github.com/FullHuman/purgecss).
Let me know there if you have any issues. I'll now archive the grunt-purgecss repository.
