### ISSUE TITLE
Show before - after size

### ISSUE THREAD

**Issue by XhmikosR** [FullHuman/grunt-purgecss#5]
Like:

```
>> 1 file created. 57.97 kB → 45.16 kB
```

**Comment by Ffloriel** [comment]
I think it's better to use another grunt plugin to print the size of the file instead of adding it in this plugin. I don't know any grunt plugin for it but there should be one.

**Comment by XhmikosR** [comment]
Please don't close this, it's a pretty simple thing to do. I mostly opened the issue so that I can track it for myself.

**Comment by XhmikosR** [comment]
But it seems purgecss doesn't expose this info, so I guess this is invalid.
